import { Card, Category } from './types';

export const categories: Category[] = [
  {
    slug: 'pokemon',
    name: 'Pokémon',
    description: 'Classic trading card game',
    cardCount: 5,
    icon: '⚡',
  },
  {
    slug: 'onepiece',
    name: 'One Piece',
    description: 'Pirate adventure TCG',
    cardCount: 5,
    icon: '🏴‍☠️',
  },
  {
    slug: 'naruto',
    name: 'Naruto',
    description: 'Ninja battle card game',
    cardCount: 4,
    icon: '🥷',
  },
  {
    slug: 'lorcana',
    name: 'Lorcana',
    description: 'Disney magical adventure',
    cardCount: 3,
    icon: '✨',
  },
  {
    slug: 'baseball',
    name: 'Baseball',
    description: 'Classic sports cards',
    cardCount: 4,
    icon: '⚾',
  },
  {
    slug: 'football',
    name: 'Football',
    description: 'NFL cards and memorabilia',
    cardCount: 4,
    icon: '🏈',
  },
  {
    slug: 'basketball',
    name: 'Basketball',
    description: 'NBA cards and collectibles',
    cardCount: 4,
    icon: '🏀',
  },
];

export const cards: Card[] = [
  // Pokémon
  {
    id: '1',
    name: 'Charizard VMAX',
    game: 'Pokémon',
    set: 'Rebel Clash',
    rarity: 'Rare Holo',
    condition: 'Near Mint',
    price: 149.99,
    image: 'linear-gradient(135deg, #ff6b35 0%, #ff2d7b 100%)',
    featured: true,
    isNew: false,
    description: 'A classic fire-breathing dragon Pokémon card in near mint condition.',
    quantity: 3,
  },
  {
    id: '2',
    name: 'Pikachu VSTAR',
    game: 'Pokémon',
    set: 'Brilliant Stars',
    rarity: 'Rare Holo V',
    condition: 'Lightly Played',
    price: 89.99,
    image: 'linear-gradient(135deg, #ffd700 0%, #ffed4e 100%)',
    featured: true,
    isNew: false,
    description: 'Electric mouse Pokémon in VSTAR form.',
    quantity: 5,
  },
  {
    id: '3',
    name: 'Mewtwo ex',
    game: 'Pokémon',
    set: 'Base Set',
    rarity: 'Ultra Rare',
    condition: 'Moderately Played',
    price: 199.99,
    image: 'linear-gradient(135deg, #9d4edd 0%, #b347ff 100%)',
    featured: false,
    isNew: true,
    description: 'Legendary psychic Pokémon in pristine condition.',
    quantity: 1,
  },
  {
    id: '4',
    name: 'Lugia V',
    game: 'Pokémon',
    set: 'Evolving Skies',
    rarity: 'Rare Holo V',
    condition: 'Near Mint',
    price: 124.99,
    image: 'linear-gradient(135deg, #4a7c9e 0%, #00f0ff 100%)',
    featured: false,
    isNew: false,
    description: 'Legendary water bird in superior condition.',
    quantity: 2,
  },
  {
    id: '5',
    name: 'Umbreon VMAX',
    game: 'Pokémon',
    set: 'Evolving Skies',
    rarity: 'Rare Holo VMAX',
    condition: 'Lightly Played',
    price: 109.99,
    image: 'linear-gradient(135deg, #1a1a2e 0%, #4a4a8a 100%)',
    featured: false,
    isNew: false,
    description: 'Dark-type evolution in excellent shape.',
    quantity: 4,
  },

  // One Piece
  {
    id: '6',
    name: 'Monkey D. Luffy (Leader)',
    game: 'One Piece',
    set: 'Starter Deck',
    rarity: 'Super Rare',
    condition: 'Near Mint',
    price: 129.99,
    image: 'linear-gradient(135deg, #ff2d7b 0%, #ff6b35 100%)',
    featured: true,
    isNew: false,
    description: 'The Straw Hat captain in powerful form.',
    quantity: 3,
  },
  {
    id: '7',
    name: 'Roronoa Zoro',
    game: 'One Piece',
    set: 'Starter Deck',
    rarity: 'Super Rare',
    condition: 'Near Mint',
    price: 99.99,
    image: 'linear-gradient(135deg, #2d5016 0%, #6fb92e 100%)',
    featured: false,
    isNew: false,
    description: 'Swordsman with three blades.',
    quantity: 2,
  },
  {
    id: '8',
    name: 'Nami',
    game: 'One Piece',
    set: 'Starter Deck',
    rarity: 'Rare',
    condition: 'Lightly Played',
    price: 59.99,
    image: 'linear-gradient(135deg, #ff9f43 0%, #ffd700 100%)',
    featured: false,
    isNew: false,
    description: 'Navigator of the Straw Hat crew.',
    quantity: 4,
  },
  {
    id: '9',
    name: 'Shanks',
    game: 'One Piece',
    set: 'Premium Collection',
    rarity: 'Ultra Rare',
    condition: 'Near Mint',
    price: 249.99,
    image: 'linear-gradient(135deg, #c41e3a 0%, #ff2d7b 100%)',
    featured: false,
    isNew: true,
    description: 'The legendary Red-haired Pirate.',
    quantity: 1,
  },
  {
    id: '10',
    name: 'Boa Hancock',
    game: 'One Piece',
    set: 'Premium Collection',
    rarity: 'Super Rare',
    condition: 'Near Mint',
    price: 119.99,
    image: 'linear-gradient(135deg, #ff1493 0%, #b347ff 100%)',
    featured: false,
    isNew: false,
    description: 'The beautiful Pirate Empress.',
    quantity: 2,
  },

  // Naruto
  {
    id: '11',
    name: 'Naruto Uzumaki',
    game: 'Naruto',
    set: 'Booster Set 1',
    rarity: 'Super Rare',
    condition: 'Near Mint',
    price: 139.99,
    image: 'linear-gradient(135deg, #ff6b9d 0%, #ffa07a 100%)',
    featured: true,
    isNew: false,
    description: 'The ninja from the Hidden Leaf Village.',
    quantity: 3,
  },
  {
    id: '12',
    name: 'Sasuke Uchiha',
    game: 'Naruto',
    set: 'Booster Set 1',
    rarity: 'Super Rare',
    condition: 'Lightly Played',
    price: 119.99,
    image: 'linear-gradient(135deg, #1a1a2e 0%, #4a4a8a 100%)',
    featured: false,
    isNew: false,
    description: 'The avenger with powerful jutsu.',
    quantity: 2,
  },
  {
    id: '13',
    name: 'Kakashi Hatake',
    game: 'Naruto',
    set: 'Booster Set 2',
    rarity: 'Rare',
    condition: 'Near Mint',
    price: 89.99,
    image: 'linear-gradient(135deg, #696969 0%, #a0a0b8 100%)',
    featured: false,
    isNew: false,
    description: 'The copy ninja with the Sharingan eye.',
    quantity: 4,
  },
  {
    id: '14',
    name: 'Itachi Uchiha',
    game: 'Naruto',
    set: 'Premium Series',
    rarity: 'Ultra Rare',
    condition: 'Near Mint',
    price: 299.99,
    image: 'linear-gradient(135deg, #2d2d44 0%, #b347ff 100%)',
    featured: false,
    isNew: true,
    description: 'The legendary Uchiha clan member.',
    quantity: 1,
  },

  // Lorcana
  {
    id: '15',
    name: 'Elsa (Spirit of Winter)',
    game: 'Lorcana',
    set: 'Into the Inklands',
    rarity: 'Super Rare',
    condition: 'Near Mint',
    price: 119.99,
    image: 'linear-gradient(135deg, #00f0ff 0%, #4a7c9e 100%)',
    featured: true,
    isNew: false,
    description: 'The ice queen in magical condition.',
    quantity: 2,
  },
  {
    id: '16',
    name: 'Mickey Mouse (Brave Little Tailor)',
    game: 'Lorcana',
    set: 'The First Chapter',
    rarity: 'Rare',
    condition: 'Lightly Played',
    price: 79.99,
    image: 'linear-gradient(135deg, #ffb6c1 0%, #ffd700 100%)',
    featured: false,
    isNew: false,
    description: 'The classic mouse in adventurer form.',
    quantity: 3,
  },
  {
    id: '17',
    name: 'Stitch (Rock Star)',
    game: 'Lorcana',
    set: 'The First Chapter',
    rarity: 'Super Rare',
    condition: 'Near Mint',
    price: 99.99,
    image: 'linear-gradient(135deg, #6b5acd 0%, #b347ff 100%)',
    featured: false,
    isNew: true,
    description: 'The alien experiment ready to jam.',
    quantity: 2,
  },

  // Baseball
  {
    id: '18',
    name: 'Mike Trout (Topps Chrome)',
    game: 'Baseball',
    set: '2023 Topps Chrome',
    rarity: 'Refractor',
    condition: 'Near Mint',
    price: 249.99,
    image: 'linear-gradient(135deg, #c41e3a 0%, #ffd700 100%)',
    featured: false,
    isNew: false,
    description: 'The Angels superstar in refractor form.',
    quantity: 1,
  },
  {
    id: '19',
    name: 'Shohei Ohtani (Prizm)',
    game: 'Baseball',
    set: '2023 Panini Prizm',
    rarity: 'Prizm Refractor',
    condition: 'Lightly Played',
    price: 199.99,
    image: 'linear-gradient(135deg, #ff6b35 0%, #ffd700 100%)',
    featured: true,
    isNew: true,
    description: 'Two-way star in shimmering condition.',
    quantity: 2,
  },
  {
    id: '20',
    name: 'Ronald Acuña Jr.',
    game: 'Baseball',
    set: '2024 Topps',
    rarity: 'Rare',
    condition: 'Near Mint',
    price: 149.99,
    image: 'linear-gradient(135deg, #ff2d7b 0%, #ffa07a 100%)',
    featured: false,
    isNew: true,
    description: 'The Braves speedster in premium condition.',
    quantity: 2,
  },
  {
    id: '21',
    name: 'Babe Ruth (Vintage)',
    game: 'Baseball',
    set: 'Heritage Collection',
    rarity: 'Ultra Rare',
    condition: 'Moderately Played',
    price: 449.99,
    image: 'linear-gradient(135deg, #8b4513 0%, #daa520 100%)',
    featured: false,
    isNew: false,
    description: 'The Sultan of Swat in classic form.',
    quantity: 1,
  },

  // Football
  {
    id: '22',
    name: 'Patrick Mahomes (Prizm)',
    game: 'Football',
    set: '2023 Panini Prizm',
    rarity: 'Prizm Refractor',
    condition: 'Near Mint',
    price: 349.99,
    image: 'linear-gradient(135deg, #e31937 0%, #ffd700 100%)',
    featured: true,
    isNew: false,
    description: 'KC Chiefs MVP in brilliant condition.',
    quantity: 1,
  },
  {
    id: '23',
    name: 'CJ Stroud (Rookie)',
    game: 'Football',
    set: '2023 Panini Select',
    rarity: 'Rookie Premier',
    condition: 'Near Mint',
    price: 179.99,
    image: 'linear-gradient(135deg, #00539b 0%, #ffd700 100%)',
    featured: false,
    isNew: true,
    description: 'Houston Texans phenom rookie.',
    quantity: 2,
  },
  {
    id: '24',
    name: 'Tyreek Hill',
    game: 'Football',
    set: '2023 Panini Prizm',
    rarity: 'Super Rare',
    condition: 'Lightly Played',
    price: 119.99,
    image: 'linear-gradient(135deg, #00a651 0%, #ffd700 100%)',
    featured: false,
    isNew: false,
    description: 'The speedy Dolphins receiver.',
    quantity: 3,
  },
  {
    id: '25',
    name: 'Saquon Barkley',
    game: 'Football',
    set: '2024 Panini Select',
    rarity: 'Super Rare',
    condition: 'Near Mint',
    price: 139.99,
    image: 'linear-gradient(135deg, #004687 0%, #00f0ff 100%)',
    featured: false,
    isNew: true,
    description: 'Eagles running back in pristine form.',
    quantity: 2,
  },

  // Basketball
  {
    id: '26',
    name: 'LeBron James (Prizm)',
    game: 'Basketball',
    set: '2023 Panini Prizm',
    rarity: 'Prizm Refractor',
    condition: 'Near Mint',
    price: 399.99,
    image: 'linear-gradient(135deg, #552583 0%, #fdb927 100%)',
    featured: true,
    isNew: false,
    description: 'The King in legendary refractor form.',
    quantity: 1,
  },
  {
    id: '27',
    name: 'Victor Wembanyama (Rookie)',
    game: 'Basketball',
    set: '2023 Panini Select',
    rarity: 'Rookie Premier',
    condition: 'Near Mint',
    price: 249.99,
    image: 'linear-gradient(135deg, #c4ced4 0%, #00f0ff 100%)',
    featured: false,
    isNew: true,
    description: 'Spurs phenom rookie sensation.',
    quantity: 2,
  },
  {
    id: '28',
    name: 'Luka Dončić',
    game: 'Basketball',
    set: '2023 Panini Donruss',
    rarity: 'Super Rare',
    condition: 'Lightly Played',
    price: 189.99,
    image: 'linear-gradient(135deg, #00338d 0%, #b8860b 100%)',
    featured: false,
    isNew: false,
    description: 'Mavericks star in fine condition.',
    quantity: 3,
  },
  {
    id: '29',
    name: 'Stephen Curry',
    game: 'Basketball',
    set: '2024 Panini Prizm',
    rarity: 'Super Rare',
    condition: 'Near Mint',
    price: 219.99,
    image: 'linear-gradient(135deg, #1d428a 0%, #fdb927 100%)',
    featured: false,
    isNew: true,
    description: 'Warriors sharpshooter in premium condition.',
    quantity: 2,
  },
];
